### ISSUE TITLE
cuando la instalo con -g igual no me la reconoce

### ISSUE THREAD

**Issue by ivanhuay** [MisaZ10/tree#1]
corri 
```
sudo npm i -g kigi
```
me devolvio
```
+ kigi@1.1.0
added 10 packages from 22 contributors in 2.833s
```

pero no me la reconoce
`Orden «kigi» no encontrada. Quizá quiso decir:`

capas le falta permisos de ejecución o algo para que la reconozca

**Comment by MisaZ10** [comment]
No esta creado para utilizarse por consola, solo es un paquete para utilizar en tu proyecto. Puede que agregue la opción mas adelante.
